
version: '3'

services:

  backend: 
    container_name: backend
    image: node:19
    # command : sh -c "tail -f /dev/null"
    command : sh -c "npm install && npm run prisma_studio && npm run start:dev"
    env_file:
      - .env
    environment:
      TEST : ${TEST}
      BACKEND_PORT : ${BACKEND_PORT}
      # JWT_SECRET: ${JWT_SERCRET}
    volumes:
      - ./backend:/backend
    working_dir: /backend
    # networks:
    #   - my_network
    ports: # -> Ne pas laisser ici sinon le web a accès au port 3306 au même titre qu'à 443. Utiliser EXPOSE dans Dockerfile !
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - 5555:5555
    # restart: unless-stopped


  # backend: # langage du back-end : node.js framework for building app
  #   container_name: backend
  #   image: backend
  #   build: ./backend
  #   env_file:
  #     - .env
    # volumes:
    #   - pongdata:/var/lib/nestjs
    # networks:
    #   - my_network
    # ports: # -> Ne pas laisser ici sinon le web a accès au port 3306 au même titre qu'à 443. Utiliser EXPOSE dans Dockerfile !
    #   - "3000:3000"
    # restart: unless-stopped

# networks:
#   my_network:
#     driver: bridge

# --------------------------------------------------------#
#                         VOLUMES                         #
# --------------------------------------------------------#

volumes:
  backend : {}